<?php
function chat_view(){
    if(isset($_POST['submitmsg'])){
        global $wpdb; // this is how you get access to the database
        //var_dump($_FILES);
        echo $_FILES['filev']['size'];
        if(isset($_FILES) && $_FILES['filev']['size']>0){
//            echo 'in';
//            var_dump($_FILES);
            if (!function_exists('wp_handle_upload')) {
                require_once(ABSPATH . 'wp-admin/includes/file.php');
            }
            // echo $_FILES["upload"]["name"];
            $allowed =  array('gif','png' ,'jpg');
            $filename = $_FILES['filev']['name'];
            $ext = pathinfo($filename, PATHINFO_EXTENSION);

            $uploadedfile = $_FILES['filev'];
            $upload_overrides = array('test_form' => false);
            $movefile = wp_handle_upload($uploadedfile, $upload_overrides);


//        echo json_encode($movefile);
            if ($movefile && !isset($movefile['error'])) {
                if(in_array($ext,$allowed) ) {
                echo "File Upload Successfully";
                $msg = '<img src="'.$movefile['url'].'" width=300 height=300>';
                }
                else {
                    $msg = '<a href="'.$movefile['url'].'" target="_BLANK">'.$_FILES['filev']['name'].'</a> ';
                }
            } else {
                /**
                 * Error generated by _wp_handle_upload()
                 * @see _wp_handle_upload() in wp-admin/includes/file.php
                 */
                echo $movefile['error'];
            }

        }
        else {

            $msg = $_POST['usermsg'];
        }
        $cid = $_POST['cid'] ;
        $table_name = $wpdb->prefix . 'chat_detail';
        $d=$wpdb->insert(
            $table_name,
            array(
                'cid' => $cid,
                'dtext' => $msg,
                'texttype' => '0',
                'notifiy' => 1
            )
        );
        //echo $d;
    }

    global $wpdb; // this is how you get access to the database
    $cid = $_GET['id'] ;
    $table_name = $wpdb->prefix . 'chat';
    $resultchat= $wpdb->get_results("select * from ".$table_name." where cid=".$cid);
    //var_dump($resultchat);
    foreach ($resultchat as $r){
        echo '<div>Name: '.$r->cnm.' &nbsp; &nbsp; &nbsp; Email: '.$r->cemail.'</div>';
    }
    $table_name = $wpdb->prefix . 'chat_detail';
    $result= $wpdb->get_results("select * from ".$table_name." where cid=".$cid);
    echo "<div id='chatbox' class='chatformadmin' style='width: 35%'>";
    foreach ($result as $r){

        if($r->texttype=='0')
            echo "<div style='float: right; width: 100%;text-align: right'>".$r->dtext."</div><br>";
        else
            echo "<div style='float: left; width: 100%;text-align: left'>".$r->dtext."</div><br>";
    }
    echo "</div>";
    $wpdb->update(
        $table_name,
        array(
            'notifiy' => '0',
        ),
        array(
            'cid' => $cid,
            'texttype' => '1'
        ));
    ?>
    <form name="message" action="" method="post" enctype="multipart/form-data" style="float: left;width: 100%">
        <input type="hidden" name="cid" id="cid" value="<?php echo $cid; ?>">
        <input name="usermsg" type="text" id="usermsg" size="63"/>
        <input type="file" id="file_upload_admin" name="filev" value="Attachment" class="btn" style="margin: 1px;" >
        <input name="submitmsg" type="submit" id="submitmsg" value="Send"/>
    </form>
<script>
    jQuery('#file_upload_admin').change(function(e){
        jQuery('#submitmsg').click();
    });
</script>

<?php


}
